// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ0VmxVaEbnJG9nc_V7H8phWuJIhFJDYE',
    appId: '1:803204172053:web:a31c2661830429327e011c',
    messagingSenderId: '803204172053',
    projectId: 'chatappsae',
    authDomain: 'chatappsae.firebaseapp.com',
    storageBucket: 'chatappsae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGzLj7-xsTgJzOMI5uMFR2wy_Esvpo5IQ',
    appId: '1:803204172053:android:a648f58aae48d8327e011c',
    messagingSenderId: '803204172053',
    projectId: 'chatappsae',
    storageBucket: 'chatappsae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7gSFJQB862_Rdi27tEEwzKLqiHZKrgAA',
    appId: '1:803204172053:ios:f17476cebf1b6c4f7e011c',
    messagingSenderId: '803204172053',
    projectId: 'chatappsae',
    storageBucket: 'chatappsae.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7gSFJQB862_Rdi27tEEwzKLqiHZKrgAA',
    appId: '1:803204172053:ios:f17476cebf1b6c4f7e011c',
    messagingSenderId: '803204172053',
    projectId: 'chatappsae',
    storageBucket: 'chatappsae.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ0VmxVaEbnJG9nc_V7H8phWuJIhFJDYE',
    appId: '1:803204172053:web:d31f36f40cd9678b7e011c',
    messagingSenderId: '803204172053',
    projectId: 'chatappsae',
    authDomain: 'chatappsae.firebaseapp.com',
    storageBucket: 'chatappsae.firebasestorage.app',
  );
}
